runtime: nodejs19
service: default
env: standard
handlers:
  - url: /build/.*
    script: auto
    secure: always
    redirect_http_response_code: 301
env_variables:
  NODE_ENV: production
  NODE_OPTIONS: --openssl-legacy-provider
